<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_comments_override' hook.

	if (post_password_required()) {
		return;
	}

 if (have_comments()) : ?>
	<section id="comments">
		<h3><?php printf(_n('One Response to &ldquo;%2$s&rdquo;', '%1$s Responses to &ldquo;%2$s&rdquo;', get_comments_number(), 'roots'), number_format_i18n(get_comments_number()), get_the_title()); ?></h3>

		<ol class="media-list">
			<?php wp_list_comments(array('walker' => new Roots_Walker_Comment)); ?>
		</ol>

		<?php if (get_comment_pages_count() > 1 && get_option('page_comments')) : ?>
		<nav>
			<ul class="pager">
				<?php if (get_previous_comments_link()) : ?>
					<li class="previous"><?php previous_comments_link(__('&larr; Older comments', 'roots')); ?></li>
				<?php endif; ?>
				<?php if (get_next_comments_link()) : ?>
					<li class="next"><?php next_comments_link(__('Newer comments &rarr;', 'roots')); ?></li>
				<?php endif; ?>
			</ul>
		</nav>
		<?php endif; ?>

		<?php if (!comments_open() && !is_page() && post_type_supports(get_post_type(), 'comments')) : ?>
		<div class="alert alert-warning">
			<?php _e('Comments are closed.', 'roots'); ?>
		</div>
		<?php endif; ?>
	</section><!-- /#comments -->
<?php endif; ?>

<?php if (!have_comments() && !comments_open() && !is_page() && post_type_supports(get_post_type(), 'comments')) : ?>
	<section id="comments">
		<div class="alert alert-warning">
			<?php _e('Comments are closed.', 'roots'); ?>
		</div>
	</section><!-- /#comments -->
<?php endif; ?>

<?php if (comments_open()) : ?>
	<section id="respond">
		<?php
			$args = array(
				'fields' => array(
					'author' => '<div class="form-group"><label for="author">' . __( 'Name', 'domainreference' ) . '</label> ' . ( $req ? '<span class="required">*</span>' : '' ) . '<input id="author" name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) . '" class="form-control"' . $aria_req . ' /></div>',
					'email'  => '<div class="form-group"><label for="email">' . __( 'Email', 'domainreference' ) . '</label> ' . ( $req ? '<span class="required">*</span>' : '' ) . '<input id="email" name="email" type="text" value="' . esc_attr(  $commenter['comment_author_email'] ) . '" class="form-control"' . $aria_req . ' /></div>',
					'url'    => '<div class="form-group"><label for="url">' . __( 'Website', 'domainreference' ) . '</label>' . '<input id="url" name="url" type="text" value="' . esc_attr( $commenter['comment_author_url'] ) . '" class="form-control" /></div>',
				),
				'comment_field' => '<div class="form-group"><label for="comment">' . __( 'Comment', 'shoestrap' ) . '</label><textarea name="comment" id="comment" class="form-control" rows="5" aria-required="true"></textarea></div>',
				'class_submit'  => 'btn',

			);
			comment_form( $args );
		?>
	</section><!-- /#respond -->
<?php endif;
