<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_header_top_navbar_override' hook.
?>
<header class="banner <?php echo SHOESTRAP_NAVBAR_CLASS; ?>" role="banner">
	<div class="<?php echo SHOESTRAP_NAVBAR_CONTAINER_CLASS; ?>">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-main, .nav-extras">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<?php
				if ( !has_action( 'shoestrap_navbar_brand_override' ) )
					echo '<a class="navbar-brand" href="' . home_url() . '/">' . get_bloginfo( 'name' ) . '</a>';
				else
					do_action( 'shoestrap_navbar_brand_override' );
			?>
		</div>

		<?php if ( has_action( 'shoestrap_pre_main_nav' ) ) : ?>
			<div class="nav-extras"><?php do_action( 'shoestrap_pre_main_nav' ); ?></div>
		<?php endif; ?>

		<nav class="nav-main navbar-collapse collapse" role="navigation">
			<?php
				do_action( 'shoestrap_inside_nav_begin' );

				$classes = apply_filters( 'shoestrap_nav_class', 'nav navbar-nav' );
				if ( has_nav_menu('primary_navigation') )
					wp_nav_menu( array( 'theme_location' => 'primary_navigation', 'menu_class' => $classes ) );

				do_action( 'shoestrap_inside_nav_end' );
			?>
		</nav>
		<?php do_action( 'shoestrap_post_main_nav' ); ?>
	</div>
</header>